services:
    libation:
        image: ceramicwhite/libation:latest
        container_name: libation
        security_opt:
        - seccomp:unconfined #optional
        stop_grace_period: 1m
        restart: on-failure
        ports:
        - 3020:3000
        volumes:
        - /ebooks/AudioBooks:/data
        - /ebooks/AudioBooks/config/libation:/config/Libation
